package mime

const (
	AudioBasic     = "audio/basic"
	AudioL24       = "audio/L24"
	AudioMP4       = "audio/mp4"
	AudioAAC       = "audio/aac"
	AudioMPEG      = "audio/mpeg"
	AudioOgg       = "audio/ogg"
	AudioVorbis    = "audio/vorbis"
	AudioWMA       = "audio/x-ms-wma"
	AudioWAX       = "audio/x-ms-wax"
	AudioRealAudio = "audio/vnd.rn-realaudio"
	AudioWAV       = "audio/vnd.wave"
	AudioWebM      = "audio/webm"

	ImageGIF   = "image/gif"
	ImageJPEG  = "image/jpeg"
	ImagePJPEG = "image/pjpeg"
	ImagePNG   = "image/png"
	ImageSVG   = "image/svg+xml"
	ImageTIFF  = "image/tiff"
	ImageICO   = "image/vnd.microsoft.icon"
	ImageWBMP  = "image/vnd.wap.wbmp"
	ImageWebP  = "image/webp"

	VideoMPEG      = "video/mpeg"
	VideoMP4       = "video/mp4"
	VideoOgg       = "video/ogg"
	VideoQuickTime = "video/quicktime"
	VideoWebM      = "video/webm"
	VideoWMV       = "video/x-ms-wmv"
	VideoFLV       = "video/x-flv"
	VideoAVI       = "video/x-msvideo"
	Video3GPP      = "video/3gpp"
	Video3GPP2     = "video/3gpp2"

	MessageHTTP    = "message/http"
	MessageIMDN    = "message/imdn+xml"
	MessagePartial = "message/partial"
	MessageRFC822  = "message/rfc822"

	ModelExample = "model/example"
	ModelIGES    = "model/iges"
	ModelMESH    = "model/mesh"
	ModelVRML    = "model/vrml"
	ModelX3DB    = "model/x3d+binary"
	ModelX3DV    = "model/x3d+vrml"
	ModelX3D     = "model/x3d+xml"

	MultipartMixed       = "multipart/mixed"
	MultipartAlternative = "multipart/alternative"
	MultipartRelated     = "multipart/related"
	MultipartFormData    = "multipart/form-data"
	MultipartSigned      = "multipart/signed"
	MultipartEncrypted   = "multipart/encrypted"

	TextCSS        = "text/css"
	TextCSV        = "text/csv"
	TextHTML       = "text/html"
	TextJavascript = "text/javascript"
	TextPlain      = "text/plain"
	TextPHP        = "text/php"
	TextXML        = "text/xml"
	TextMarkdown   = "text/markdown"
	TextManifest   = "text/cache-manifest"

	ApplicationAtom        = "application/atom+xml"
	ApplicationEDIX12      = "application/EDI-X12"
	ApplicationEDIFACT     = "application/EDIFACT"
	ApplicationJSON        = "application/json"
	ApplicationJavaScript  = "application/javascript"
	ApplicationOctetStream = "application/octet-stream"
	ApplicationOgg         = "application/ogg"
	ApplicationPDF         = "application/pdf"
	ApplicationPostScript  = "application/postscript"
	ApplicationSOAP        = "application/soap+xml"
	ApplicationWOFF        = "application/font-woff"
	ApplicationXHTML       = "application/xhtml+xml"
	ApplicationDTD         = "application/xml-dtd"
	ApplicationXOP         = "application/xop+xml"
	ApplicationZIP         = "application/zip"
	ApplicationGZip        = "application/gzip"
	ApplicationBitTorrent  = "application/x-bittorrent"
	ApplicationTeX         = "application/x-tex"
	ApplicationXML         = "application/xml"
	ApplicationDOC         = "application/msword"

	ApplicationFormEncodedData = "application/x-www-form-urlencoded"
	ApplicationDVI             = "application/x-dvi"
	ApplicationLaTeX           = "application/x-latex"
	ApplicationTrueType        = "application/x-font-ttf"
	ApplicationAdobeFlash      = "application/x-shockwave-flash"
	ApplicationStuffIt         = "application/x-stuffit"
	ApplicationRAR             = "application/x-rar-compressed"
	ApplicationTarball         = "application/x-tar"
	TextJQueryTmpl             = "text/x-jquery-tmpl"

	ApplicationP12 = "application/x-pkcs12"
	ApplicationP7B = "application/x-pkcs7-certificates"
	ApplicationSPC = "application/x-pkcs7-certificates"
	ApplicationP7R = "application/x-pkcs7-certreqresp"
	ApplicationP7C = "application/x-pkcs7-mime"
	ApplicationP7S = "application/x-pkcs7-signature"
)
